<?php require_once __DIR__.'/../layouts/header.php'; mostrarFlash(); ?>
<?php if($modoAdmin && !$tutorSeleccionado): ?>
<div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><span class="eyebrow">Agenda académica</span><h1 class="page-title mb-1">Horarios de tutores</h1><p class="text-muted mb-0">Selecciona un tutor para consultar sus bloques de disponibilidad. La administración solo tiene acceso de consulta.</p></div></div>
<div class="card card-custom overflow-hidden"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Tutor</th><th>Usuario</th><th>Estado</th><th>Horarios registrados</th><th class="text-end">Consultar</th></tr></thead><tbody>
<?php foreach($tutores as $t): ?><tr><td><a class="fw-semibold text-decoration-none" href="disponibilidad_listar.php?tutor_id=<?=$t['id_tutor']?>"><?=e($t['nombre'].' '.$t['apellido'])?></a></td><td class="text-muted">@<?=e($t['usuario'])?></td><td><span class="badge text-bg-<?=estadoBadge($t['estado'])?>"><?=e(estadoEtiqueta($t['estado']))?></span></td><td><span class="badge text-bg-light border"><?=e($t['total_horarios'])?> bloque(s)</span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="disponibilidad_listar.php?tutor_id=<?=$t['id_tutor']?>"><i class="bi bi-calendar-week me-1"></i>Ver horarios</a></td></tr><?php endforeach; if(!$tutores): ?><tr><td colspan="5" class="text-center py-5 text-muted">No hay tutores registrados.</td></tr><?php endif; ?></tbody></table></div></div>
<?php else: ?>
<div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><span class="eyebrow">Agenda académica</span><h1 class="page-title mb-1"><?=esTutor()?'Mi disponibilidad':'Horario del tutor'?></h1><p class="text-muted mb-0"><?=e(($tutorSeleccionado['nombre']??'').' '.($tutorSeleccionado['apellido']??''))?> · Bloques disponibles para programar tutorías.</p></div><div class="d-flex gap-2"><?php if($modoAdmin): ?><a href="disponibilidad_listar.php" class="btn btn-outline-secondary">Volver a tutores</a><?php else: ?><a href="disponibilidad_crear.php" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i>Nuevo horario</a><?php endif; ?></div></div>
<div class="card card-custom overflow-hidden"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Día</th><th>Inicio</th><th>Fin</th><?php if(esTutor()): ?><th class="text-end">Acciones</th><?php endif; ?></tr></thead><tbody>
<?php foreach($registros as $r): ?><tr><td><span class="badge bg-primary-subtle text-primary"><?=e($r['dia_semana'])?></span></td><td><?=e(substr($r['hora_inicio'],0,5))?></td><td><?=e(substr($r['hora_fin'],0,5))?></td><?php if(esTutor()): ?><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="disponibilidad_editar.php?id=<?=$r['id_disponibilidad']?>"><i class="bi bi-pencil"></i></a> <form class="d-inline" method="POST" action="disponibilidad_eliminar.php" onsubmit="return confirm('¿Eliminar este horario?')"><?=csrfField()?><input type="hidden" name="id" value="<?=$r['id_disponibilidad']?>"><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td><?php endif; ?></tr><?php endforeach; if(!$registros): ?><tr><td colspan="<?=esTutor()?4:3?>" class="text-center py-5 text-muted">No hay horarios registrados para este tutor.</td></tr><?php endif; ?></tbody></table></div></div>
<?php endif; ?>
<?php include __DIR__.'/../layouts/footer.php'; ?>
